# Generated by Django 3.2.9 on 2021-11-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='request/')),
                ('content', models.TextField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('start_price', models.IntegerField(default=0)),
                ('end_price', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='userapp.user')),
            ],
        ),
    ]
